### ISSUE TITLE
Calling `close` in `onDisconnect` callback doesn't stop it from reconnecting

### ISSUE THREAD

**Issue by uyha** [rexxars/eventsource-client#3]
I have a small snippet like the following

```typescript
let es = createEventSource({
		url: `someurl`,
		onDisconnect: () => {
			console.log('here');
			es.close();
		}
	});
```

On the console, "here" is still being printed out continuously.

**Comment by rexxars** [comment]
Good find! Fixed in [v1.1.2](https://github.com/rexxars/eventsource-client/releases/tag/v1.1.2) - thanks!
